// Code generated by goctl. DO NOT EDIT.
package types

type CreateClockinReq struct {
	Uid               string `json:"uid,required"`
	Title             string `json:"title,required"`
	Description       string `json:"description,required"`
	WordCount         int    `json:"word_count,required"`
	Cover             string `json:"cover"`
	StartDay          string `json:"start_day"`
	EndDay            string `json:"end_day"`
	ClockinStartDaily string `json:"clockin_start_daily,required"`
	ClockinEndDaily   string `json:"clockin_end_daily"`
	TotalFee          uint64 `json:"total_fee"`
	BonusDaily        uint64 `json:"bonus_daily"`
}

type CreateClockinResp struct {
}

type CreateContentReq struct {
	Content string `json:"content,required"`
	Cid     string `json:"cid,required"`
}

type CreateContentResp struct {
}

type SigninReq struct {
	LoginMethod string `json:"login_method"`
	MixinToken  string `json:"mixin_token,optional"`
	Sign        string `json:"sign,optional"`
	SignedMsg   string `json:"sign_msg,optional"`
}

type SigninResp struct {
	Token string `json:"token"`
}

type User struct {
	IdentityNumber string `json:"identity_number"`
	Uid            string `json:"uid"`
	FullName       string `json:"full_name"`
	AvatarUrl      string `json:"avatar_url"`
	Biography      string `json:"biography"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type CreateUserReq struct {
	IdentityNumber string `json:"identity_number"`
	Uid            string `json:"uid"`
	FullName       string `json:"full_name"`
	AvatarUrl      string `json:"avatar_url"`
	Biography      string `json:"biography"`
}
